alias workspace="cd ${GITPOD_REPO_ROOT}"
alias temporal="/workspace/bin/temporal"
alias tctl="/workspace/bin/tctl"
alias webui="gp preview $(gp url 8080)"
export PATH="$PATH:/home/gitpod/.temporalio/bin"
echo "temporal configured! try typing temporal -v"
echo "Your workspace is located at: ${GITPOD_REPO_ROOT}"
echo "Type the command     workspace      to return to the workspace directory at any time."